name: DEV deploy

on:
  push:
    branches: [ master ]
  watch:
    types: [ started ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.actor == github.event.repository.owner.login
    steps:
    - name: SSH docker-compose pull
      uses: appleboy/ssh-action@v0.0.2
      host: ${{ secrets.DEV_HOST_IP }}
      username: ec2-user
      key: ${{ secrets.DEV_SSH_KEY }}
      script: |
        docker-compose pull
        docker-compose up -d stall-spa
