name: Start action

on:
        #  push:
        #    branches: [ master ]
  watch:
    types: [ started ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.actor == github.event.repository.owner.login      
    steps:
     - run: |
         echo ::debug::Random link https://ya.ru/test-out
#    - uses: actions/checkout@master
#    - uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#        files: ./coverage1.xml,./coverage2.xml # optional
#        flags: unittests # optional
#        name: codecov-umbrella # optional
#        fail_ci_if_error: true # optional (default = false)
#        verbose: true # optional (default = false)
